"use strict";
import chai = require("chai");
import TransformFile = require("../file-io/TransformFile");

var asr = chai.assert;

type MatchOperation = TransformFile.MatchOperation;

suite("TransformFile", function TransformFileTest() {

    test("transformLines", function transformLinesTest() {
        var srcLines = [
            "/** This file contains templates and was generated by $generator$",
            " */",
            "var Model = {",
            "$fields$",
            "",
            "$methods$",
            "",
            "};"
        ];
        var resLines = TransformFile.transformLines("DummyFileA.ts", srcLines, "$", "$", {
                "generator": { op: TransformFile.MatchOperation.REPLACE_MATCHING_PORTION, opParam: "ts-file-io" },
                "fields": { op: TransformFile.MatchOperation.REPLACE_MATCHING_PORTION, opParam: ["  id: 1,", "  name: 'abc',", "  active: true,"] },
                "methods": { op: TransformFile.MatchOperation.REPLACE_MATCHING_PORTION, opParam: ["  toString: function () { return this.name; }"] },
        });

        var ln = "\n";
        asr.equal(resLines.join(ln), ["/** This file contains templates and was generated by ts-file-io",
            " */",
            "var Model = {",
            "  id: 1,",
            "  name: 'abc',",
            "  active: true,",
            "",
            "  toString: function () { return this.name; }",
            "",
            "};"
        ].join(ln));
    });

});
